In [1]:
APPID = "85Uh7txOAZ0eBSBmisR55m5aKNh+0QnfHRgFsSTmLznvZvQIy5aSJg=="
APIKey = "cGEErDNy5yOV6QBnBTBMw08hkep+XQWXUPDYVruKLnfMQTtX884myy67TFORCc+1ugS8LAB1wXnAx2C0ju8g2YpKG81bknXjqwRFvcUkgfjVbi3MZZfFb5ciwEoNghOkzF7mNe+ZMa1BB43M09Q0GF7VDyu9V9YO/qmBwvyyNpquVG99q0df4KZ4cHqUqxiLYZ6YC81G6DsX2BdzlfDX5j58d5Cjyp8UMYFM3bnkjR4FT/rvBbdmzjHMFXZpz1Hgw7ARaDn2bIPCz5eh8+RcZubCNjUlieoFJNQU1h8nF6g7W3YUy+2F54AJ7Evc/+n3nSS+QUswIbpyFTWAJmS3++7fDF9SmbqovsGrYsk9sctP5aiLVQEXnT3phO872sRud/RNZz5PEAjE5Tyx12nLcE2WeiFGD6RzxAKoV+ZW5eY="

In [2]:
import pandas as pd

old = pd.read_csv("臺北市.csv", low_memory= False)
new = pd.read_csv("臺北市113.csv", low_memory= False)
df = pd.concat([old,new], ignore_index=True)

In [3]:
# 獲取第一個出現的建案名稱及地址
first_project_name = df.iloc[0]['建案名稱']  # 第一個建案名稱
first_address = df.iloc[0]['座落']  # 第一個對應的地址

# 打印結果
print(f"第一個出現的建案名稱: {first_project_name}")
print(f"對應的地址: {first_address}")

第一個出現的建案名稱: 菁席
對應的地址: 中正區仁愛路二段44號

In [4]:
# 使用 groupby 獲取每個不同建案名稱的第一個地址
unique_projects = df.groupby('建案名稱')['座落'].first().reset_index()
unique_projects[["地址","tmp"]] = unique_projects['座落'].str.split("號",n=1 , expand= True)
unique_projects["地址"] = "臺北市" + unique_projects["地址"]+ "號"

import unicodedata

# 定義一個函數來將全形字符轉換為半形字符
def to_half_width(s):
    return unicodedata.normalize('NFKC', s)

# 假設 '座落' 列中包含全形字符，將其轉換為半形字符
unique_projects['地址'] = unique_projects['地址'].apply(to_half_width)
unique_projects.drop(columns = ["座落","tmp"],inplace = True)
# 打印結果
display(unique_projects)

               建案名稱                      地址
0              30創富            臺北市萬華區康定路84號
1        55TIMELESS          臺北市信義區信義路五段57號
2               BR4        臺北市大安區復興南路一段175號
3    ForestPark吉美富徠          臺北市大安區瑞安街155巷號
4             H24雲端         臺北市北投區中央南路二段14號
..              ...                     ...
763      鼎吉中山VISION           臺北市中山區新生北路二段號
764            鼎吉水岸         臺北市中正區水源路161-1號
765             鼎隆苑  臺北市文山區興隆路二段25巷乙棟I-11F號
766            龍霖初心        臺北市北投區石牌路二段315巷號
767              美           臺北市文山區景後街178號

[768 rows x 2 columns]

In [5]:
unique_projects.to_csv("query.csv")

In [6]:
query = pd.read_csv("Address_Finish.csv", low_memory= False)

In [7]:
list(query.columns)
for i in ['id', 'Address', 'Response_Address', 'Response_X', 'Response_Y']:
    print (i)

id
Address
Response_Address
Response_X
Response_Y

# 使用 str.split 分割
split_columns = query["Response_Address"].str.split(";", expand=True)

for i in ['Response_Address', 'Response_X', 'Response_Y'] :
    query[i] = query[i].apply(lambda x: x.split(";")[-1] if pd.notnull(x) else x)

In [8]:
query["p_name"] = unique_projects['建案名稱']
query.drop(columns = "id")
query = query[["p_name","Address","Response_Address","Response_X","Response_Y"]]

In [9]:
query.rename(columns = {"Response_X" :"x","Response_Y":"y"}, inplace = True)
query

,p_name,Address,Response_Address,x,y
0,30創富,臺北市萬華區菜園里12鄰康定路84號,臺北市萬華區菜園里12鄰康定路84號,121.502230,25.041989
1,55TIMELESS,臺北市信義區安康里9鄰信義路五段57號,臺北市信義區安康里9鄰信義路五段57號,121.569432,25.033321
2,BR4,臺北士林區舊佳里文林路584號,臺北市士林區舊佳里22鄰文林路582號,121.523874,25.098205
3,ForestPark吉美富徠,臺北市內湖區江南街65巷25號之1,臺北市內湖區港墘里5鄰江南街65巷25之1號,121.578142,25.077096
4,H24雲端,臺北市中山區正守里12鄰長安東路一段52巷10號,臺北市中山區正守里12鄰長安東路一段52巷10號,121.527835,25.047751
...,...,...,...,...,...
762,鼎吉中山,臺北市中山區吉林路316號,臺北市中山區新生里13鄰吉林路316號,121.530141,25.062252
763,鼎吉中山VISION,臺北市中山區吉林路316號,臺北市中山區新生里13鄰吉林路316號,121.530141,25.062252
764,鼎吉水岸,臺北市中正區螢雪里12鄰水源路165之2號,臺北市中正區螢雪里12鄰水源路165之2號,121.514973,25.024090
765,鼎隆苑,臺北市文山區興豐里10鄰興隆路二段25巷20之1號,臺北市文山區興豐里10鄰興隆路二段25巷20之1號,121.545682,24.999786
766,龍霖初心,臺北市北投區永欣里13鄰石牌路二段315巷6之3號,臺北市北投區永欣里13鄰石牌路二段315巷6之3號,121.522989,25.122212

In [10]:
query.to_csv("queryed.csv",index  = False)